name: Generate JSON files

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Start Redis
      run: |
        curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
        sudo apt-get update
        sudo apt-get install redis-stack-server
        sudo apt-get install -y redis
        redis-server --port 29384 &

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Generate JSON files
      run: |
        pip install redis
        python convert.py

    - name: Update database
      uses: actions-x/commit@v6
      with:
        email: github-actions@noreply.github.com
        name: github-actions
        message: 'update database'
        branch: main
        files: .
        token: ${{ secrets.GITHUB_TOKEN }}
        force: true