name: Trigger All Branches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Get branch name
      run: echo "branch=${GITHUB_REF#refs/heads/}" >>$GITHUB_ENV

    - name: Run the trigger
      uses: bash update_all_branches.sh

    - name: Update log
      uses: actions-x/commit@v6
      with:
        email: github-actions@noreply.github.com
        name: github-actions
        message: 'update log'
        branch: ${{ env.branch }}
        files: .
        token: ${{ secrets.GITHUB_TOKEN }}
        force: true