name: Update topics of a douban group

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Get branch name
      run: |
        echo "branch=${GITHUB_REF#refs/heads/}" >>$GITHUB_ENV
        echo ${{ env.branch }}
    
    - name: Start Redis
      run: |
        sudo apt-get install -y redis
        cd data
        redis-server --port 13849 &

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Crawl douban group
      run: |
        pip install redis
        pip install scrapy
        scrapy crawl douban-group

    - name: Update database
      uses: actions-x/commit@v6
      with:
        email: github-actions@noreply.github.com
        name: github-actions
        message: 'update database'
        branch: main
        files: .
        token: ${{ secrets.GITHUB_TOKEN }}
        force: true